name: Unit Tests
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  unit-tests:
    runs-on: windows-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        id: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: src/global.json

      - name: Setup report generator
        run: dotnet.exe tool install -g dotnet-reportgenerator-globaltool

      - name: Run CLI tests
        run: |
          cd src
          dotnet.exe test `
            --project .\Tests.Cli\Tests.Cli.csproj `
            --configuration Debug `
            --runtime win-x64 `
            --output Detailed `
            --diagnostic `
            --diagnostic-output-directory diags `
            --report-trx `
            --coverage `
            --coverage-settings .\testconfig.json

      - name: Run Application tests
        run: |
          cd src
          dotnet.exe test `
            --project .\Tests.Application\Tests.Application.csproj `
            --configuration Debug `
            --runtime win-x64 `
            --output Detailed `
            --diagnostic `
            --diagnostic-output-directory diags `
            --report-trx `
            --coverage `
            --coverage-settings .\testconfig.json

      - name: Run report generator
        if: always()
        run: |
          reportgenerator.exe `
            -reports:**/*.cobertura.xml `
            -targetdir:${{ github.workspace }}/coveragereport `
            '-reporttypes:Cobertura;HtmlInline;MarkdownSummary' `
            '-title:Code Coverage' `
            -tag:${{ github.run_number }}_${{ github.run_id }}

      - name: Upload test result artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: test-results
          path: |
            ${{ github.workspace }}/**/diags/**/*
            ${{ github.workspace }}/**/TestResults/**/*
          if-no-files-found: error

      - name: Upload coverage report artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: coverage-report
          path: ${{ github.workspace }}/**/coveragereport/**/*
          if-no-files-found: error

      - name: Add coverage pr comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: ${{ github.workspace }}/coveragereport/Summary.md
